export const VERSION_SHORT = 'SYS.V.1.0';
export const VERSION_LONG = 'SYSTEM ARCHIVE V.01';
export const EST_ROMAN = 'EST. MMXVI';
export const LOCATION = 'LOS ANGELES';
export const COPYRIGHT = '© 2016 MINDLESS SCRIBBLES INCORPORATED';
